FROM gitlab/gitlab-runner:alpine-v10.6.0-rc1

RUN apk add --update ansible openssh sshpass docker sudo

RUN mkdir /etc/ansible

ADD ansible.cfg /etc/ansible/ansible.cfg

CMD ["run", "--user=gitlab-runner", "--working-directory=/home/gitlab-runner"]
