FROM gitlab/gitlab-runner:alpine-v10.6.0-rc1

RUN echo "http://dl-cdn.alpinelinux.org/alpine/latest-stable/community" >> /etc/apk/repositories && \
        apt update && \
	apt install ansible openssh sshpass docker sudo

RUN mkdir /etc/ansible

ADD ansible.cfg /etc/ansible/ansible.cfg

RUN echo "gitlab-runner ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

CMD ["run", "--user=gitlab-runner", "--working-directory=/home/gitlab-runner"]

